spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_MOVIETABLE}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
